### ISSUE TITLE
Solution out of sync with master.

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/ruby-vs-js-array-methods-study#1]
Currently 5 commits behind and 7 commit ahead.

**Comment by jordanallain** [comment]
should i hold off on opening a PR for lm01/solution into solution?

**Comment by gaand** [comment]
Why?

**Comment by jordanallain** [comment]
wasn't sure if we should try to fix the solution branch being the incorrect number of commits away, will continue as normal.

**Comment by jrhorn424** [comment]
Looks like we're in sync now.
