### ISSUE TITLE
Tests fail: Functions tested are not being invoked with () in spec

### ISSUE THREAD

**Issue by joaufi** [ga-wdi-boston/ruby-vs-js-array-methods-study#16]
For each test in Mocha the functions being tested are missing their `()` at the end of them so they are not being invoked, and thus they are not working. The tests fail with:
```
1) sumFibs is the sum of the fibs array:
     AssertionError: expected [Function] to equal 88
      at Context.<anonymous> (spec/fibonacci.spec.js:17:35)
```

E.g.:
// Not working
```js
describe('sumFibs', function () {
  it('is the sum of the fibs array', function () {
    expect(fibResults.sumFibs).to.equal(88);
  });
});

// Working
describe('sumFibs', function () {
  it('is the sum of the fibs array', function () {
    expect(fibResults.sumFibs()).to.equal(88);
  });
});
```

I changed them so they now work and will put a note in my Pull Request.

**Comment by raq929** [comment]
Actually, the tests were not expecting you to write a function, just
deliver a result via array methods. Check the solution branch. :)

**Comment by raq929** [comment]
This may be a fault in the directions.

**Comment by joaufi** [comment]
It doesnt explicitly state to write functions in the directions, but perhaps should be noted to simply store the resulting value that is being tested for in the file? Mostly because we have typically been using Grunt Test to tests functions. Thanks for looking into it tho! Closing~

**Comment by raq929** [comment]
Please reopen so we can remember to be more explicit in the directions next
time around. :)

**Comment by jrhorn424** [comment]
👏 😄
